### ISSUE TITLE
Plan total disk encryption for new stack

### ISSUE THREAD

**Issue by kenners** [uamuzibora/nafasi#27]
We need a bombproof how-to on how to setup our disk encryption for our deployment server.

Previously we followed (and adapted IIRC) these instructions:
http://wejn.org/how-to-make-passwordless-cryptsetup.html

We also need to ensure that any packages we need are stored in our apt repo (see #17).

**Comment by kenners** [comment]
Again, I'm thinking @andrewlkho is best placed for this one - is that ok?

**Comment by andrewlkho** [comment]
I've started a stub page on the [kasha wiki](https://github.com/uamuzibora/kasha/wiki/Total-disk-encryption).  To move it forward I'll need to familiarise myself with the actual install process of ubuntu (something that I've never done before).  Hopefully this can be done with virtualbox.  Otherwise the last mile might need a physical box for testing which may well end up being in-country as I don't have one readily available.

**Comment by andrewlkho** [comment]
This is now documented on the kasha wiki.
